version: "3"
services:
  server:
    build: server/
    command: json-server db.json -p 4000
    ports:
      - 4000:4000
  client:
    build: client/
    command: npm start
    network_mode: host
    environment:
      REACT_APP_BASE_URL: "http://localhost"
      REACT_APP_PORT: 4000
    depends_on:
      - server
