services:
  - name: json-server
    type: web
    env: docker
    dockerfilePath: server/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 4000

  - name: react-client
    type: web
    env: docker
    dockerfilePath: client/Dockerfile
    plan: free
    envVars:
      - key: REACT_APP_BASE_URL
        value: https://json-server-5qjw.onrender.com
      - key: REACT_APP_PORT
        value: 4000
