services:
  - name: json-server
    type: web
    env: docker
    dockerfilePath: server/Dockerfile
    plan: free

  - name: react-client
    type: web
    env: docker
    dockerfilePath: client/Dockerfile
    plan: free
